version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - webdata:/data
    networks:
      - webnet

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  webdata:
  pgdata:

networks:
  webnet: